analyzer:
  plugins:
    - custom_lint
  errors:
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore
    unused_import: warning
    unused_local_variable: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_final_locals: warning
    prefer_final_fields: warning
    avoid_print: warning 
    always_declare_return_types: warning

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_fields: true
    unnecessary_this: true

    avoid_redundant_argument_values: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    omit_local_variable_types: false
    always_specify_types: false

    lines_longer_than_80_chars: false
    require_trailing_commas: true
    curly_braces_in_flow_control_structures: true
    unnecessary_lambdas: true
    avoid_positional_boolean_parameters: false
    avoid_setters_without_getters: true

    avoid_dynamic_calls: false
    avoid_null_checks_in_equality_operators: true
    avoid_bool_literals_in_conditional_expressions: true

    prefer_const_literals_to_create_immutables: true
    use_key_in_widget_constructors: true
    avoid_print: true
